### ISSUE TITLE
Enforce unique blockchain addresses among test actors

### ISSUE THREAD

**Issue by andrewgordstewart** [statechannels/statechannels#1733]
We can eg. use a file named something like `$MONOREPO/.addressesInUse/$GANACHE_PORT/$SIGNING_ADDRESS` to mark a signing address as being _in use_ when running a test that's using a local ganache server. This can enforce that a given signing address is only used once, preventing concurrency issues like  https://github.com/statechannels/monorepo/issues/1577.

**Comment by kerzhner** [comment]
Related to https://github.com/statechannels/monorepo/issues/1715

**Comment by lalexgap** [comment]
Another alternative (originally mentioned by @kerzhner) is that we could use random addresses and fund them from a known funded address in test setup.

I was also looking if we could use a fixed mnemonic in ganache for funding and then use that to create a `HDWallet` where we could generate some arbitrary funded address. However since address generation is deterministic we'd need to randomly pick one of the HDWallet's address, so I'm not sure if collisions could still be an issue?

**Comment by geoknee** [comment]
I'm no sure the hd wallet helps to create **funded** accounts?

**Comment by lalexgap** [comment]
> I'm no sure the hd wallet helps to create **funded** accounts in any case?

I think `ganache-cli` accepts a mnemonic to create the funded acccounts. So using an HDWallet with that mneomic would give you all the possible funded accounts, but let me verify the ganche-cli behaviour.

**Comment by geoknee** [comment]
Ah interesting

**Comment by lalexgap** [comment]
> > I'm no sure the hd wallet helps to create **funded** accounts in any case?
> 
> I think `ganache-cli` accepts a mnemonic to create the funded acccounts. So using an HDWallet with that mneomic would give you all the possible funded accounts, but let me verify the ganche-cli behaviour.

Just confirmed, I started `ganache-cli` with my metmask mnemonic and every account created by metamask started at `100ETH`

**Comment by andrewgordstewart** [comment]
> Another alternative (originally mentioned by @kerzhner) is that we could use random addresses and fund them from a known funded address in test setup.

Using random addresses is a good way to uses different addresses, but I'd also advocate that we _enforce_ different addresses so that this mistake creates a loud, obvious error.

**Comment by lalexgap** [comment]
> Using random addresses is a good way to uses different addresses, but I'd also advocate that we _enforce_ different addresses so that this mistake creates a loud, obvious error.

If addresses are sufficiently random do we need to bother with the infrastructure to catch this now? I think it'll be easy enough to realize `transaction nonce` issues are caused by address reuse?

**Comment by andrewgordstewart** [comment]
Yes, if we _remember_ to use the random addresses.

**Comment by lalexgap** [comment]
> Yes, if we _remember_ to use the random addresses.

I guess my opinion is that if we're using a properly random addresses then it's not worth adding infrastructure to catch the case where someone forgot to do that.

On the other hand if we're just picking an address from a list of 10 or we pass into `ganache-cli` then I think it's worth checking we're not reusing an address since that's likely to happen.

**Comment by andrewgordstewart** [comment]
A compromise would be:
- the tooling _enforces_ that you uses random addresses
