### ISSUE TITLE
Memory Leaks in Persistent Seeder

### ISSUE THREAD

**Issue by spersico** [statechannels/statechannels#1755]
![image](https://user-images.githubusercontent.com/10502605/81446998-33c33b80-9152-11ea-9963-f131fe4d7d56.png)
The heroku admin is showing this, it might point to a memory leak

**Comment by snario** [comment]
As a band-aid can we refresh the persistent seeder every `x` minutes?

**Comment by andrewgordstewart** [comment]
This is probably just due to logging. Or, at the very least, logging to `console` _will cause memory leaks_, since objects that are logged to `console` will never be garbage collected.

**Comment by snario** [comment]
Note this did not do what we want as logs are still going to be inside the Chromium tab because the settings are in `.env.production-ropsten` not `.env.persistent-seeder`

**Comment by andrewgordstewart** [comment]
> Note this did not do what we want as logs are still going to be inside the Chromium tab because the settings are in `.env.production-ropsten` not `.env.persistent-seeder`

That's a bit confusing 😆

**Comment by kerzhner** [comment]
It sounds like this is an issue with local browsers as well. Course of action:
1. Reproduce memory bloat locally.
1. Turn off all logging to understand if the logging is the cause of memory bloat.
1. If logging is the cause of memory bloat, be more selective about logging levels and logging thresholds. Use `debug` and `trace` methods instead of always using `info`.

**Comment by tomclose** [comment]
For launch we just need that the persistent seeder works. As long as this doesn't stop it from seeding most of the time, we can probably leave it.
