### ISSUE TITLE
Audit wallet's current emission of ChannelUpdated events

### ISSUE THREAD

**Issue by snario** [statechannels/statechannels#1891]
It would be useful to have a table that shows what conditions cause `ChannelUpdated` to emit. Is it only when `turnNum`s increase? What about when challenges are created? etc

**Comment by geoknee** [comment]
https://github.com/statechannels/monorepo/blob/master/packages/client-api-docs/source/index.html.md#channel-updated

^ expected behaviour is documented here, but I have not checked that the wallet conforms to it.

Actual behaviour is affected by:
https://github.com/statechannels/monorepo/blob/f9b2805ffc8b257d21d22793d62ae4d4058e0936/packages/xstate-wallet/src/workflows/application.ts#L270-L282

So the docs should probably be updated to reflect this. Something along the lines of "this event is emitted if and only if one of the following fields has changed
```    
    participants,  // cannot change
    allocations: serializeAllocation(outcome),
    appDefinition, // cannot change
    appData,
    status,
    turnNum: formatAmount(turnNum),
    channelId // cannot change
```
"
