### ISSUE TITLE
Figure out ChannelResults/ChannelNotifications and make them consistent

### ISSUE THREAD

**Issue by lalexgap** [statechannels/statechannels#2432]
[This code](https://github.com/statechannels/statechannels/blob/master/packages/client-api-schema/src/data-types.ts#L106-L125) is not documented, and it's not 100% clear what each status means.

**Comment by andrewgordstewart** [comment]
As far as I can tell, we actually want a data structure more like this:

```
type Variables = {
  allocations: Allocation[];
  appData: string;
  turnNum: Uint48;
};
export type ChannelStatus = {
  type:
    | 'proposed' // MEANS: prefund setup not signed by me
    | 'opening' // MEANS: prefund setup signed by me, but not supported
    | 'funding' // MEANS: prefund setup supported, postfund setup not supported
    | 'running' // MEANS: postfund setup supported
    | 'closing' // MEANS: supported final state
    | 'closed'; // MEANS: conclusion proof
} & Variables;
export type AdjudicatorStatus =
  | {type: 'open'; turnNum: Uint48}
  | ({
      type:
        | 'challenging' // MEANS a challenge is ongoing, and it's not my turn
        | 'responding'; // MEANS a challenge is ongoing, and it's my turn
      challengeExpirationTime: number;
    } & Variables)
  | ({type: 'closed'} & Variables);
export interface ChannelResult {
  channelId: ChannelId;
  participants: Participant[];
  appDefinition: Address;
  channelStatus: ChannelStatus;
  adjudicatorStatus: AdjudicatorStatus;
}
```
## Reasoning
1) When there is a challenge registered on chain, the state might be unrelated to the latest supported state we have (or just the latest state, if we have no supported state)
2) There is a distinction between
  A. "Someone (maybe me) wants to close the channel, because they signed a final state" 
  B. "I have the ability to instantly close the channel, because I have a conclusion proof"
  C. "The channel is finalized on chain. Nothing more can be done"
3) If I receive two results for a channel, one where the turn number is 10 and one where it's 12, I might not actually know which one takes precedence with the current `ChannelResult` interface -- if the turn 10 result has a `'challenging'` status, then it might be more recent than the turn 12 result

All of these issues are dealt with by having orthogonal two orthogonal `ChannelStatus` and `AdjudicatorStatus` properties.

(3) is resolved because this separation allows you to _merge_ results if need be by taking the maximum turn number. This is possible (in the `ChannelStatus`) when the wallet maintains the invariant that there is at most one supported state.

## Open questions
1. Should the channel result indicate whether or not the channel is unfunded?
2. Are these names good? Maybe `channelStatus -> channel` and `adjudicatorStatus -> chain`, or something like that, could be better names

**Comment by snario** [comment]
> Maybe adjudicatorState.type === 'close' means that the channel is unfunded?
I don't think that makes sense? Most unfunded channels will not have any adjudicator state unless there was a challenge

**Comment by andrewgordstewart** [comment]
> > Maybe adjudicatorState.type === 'close' means that the channel is unfunded?
> 
> I don't think that makes sense? Most unfunded channels will not have any adjudicator state unless there was a challenge

`adjudicatorState` may be a bad name for it (see open question 2). But nevertheless, there is still a difference between
- "I can finalize the channel instantly on chain"; and
- "the channel is 'finished' -- I can stop worrying about it"

where 'finished' might mean it is finalized on chain and you have withdrawn, or it might mean that the channel is unfunded and the ledger channel is updated

**Comment by andrewgordstewart** [comment]
## More open questions
3. How does the app learn that a channel that _was_ virtually funded is _now_ directly funded, because the ledger channel became finalized on chain? Should the app care?

**Comment by andrewgordstewart** [comment]
Here is another interim solution: let's agree on an interpretation like this:
```
export type ChannelStatus =
  | 'proposed' // The wallet is storing this channel, but you have not.
  | 'opening' // You have joined the channel, but it's not ready to use.
  | 'funding' // Same as 'opening'. These statuses are basically irrelevant anyway.
  | 'running' // You are free to use the channel.
  | 'challenging' // You cannot use the channel right now. There is a challenge ongoing, but you do not need to do anything.
  | 'responding' // There is a challenge ongoing, and you must call `updateChannel` in order for the wallet to respond to the challenge.
  | 'closing' // You cannot use the channel anymore, but your funds are still locked up.
  | 'closed'; // Your funds have been released from the channel.
```

We can choose to ignore how to order results, in case of some weirdness, or we can add an incrementing `resultId` field on the result, so that it's obvious which result takes precedence.

**Comment by andrewgordstewart** [comment]
I am going to go with this ^

**Comment by LayneHaber** [comment]
So I'm jumping in a little late here, but I want to resurface this issue. I'm not understanding the reason for the workaround, and I don't think these statuses are necessarily the best convention. After reading this, it's still not clear to be what `opening` vs `funding` means, and I'm not sure what other statuses are meant by `"these statuses"`

Would like to arrive at a finalized channel status model when we make settle on the spec in #2489
