### ISSUE TITLE
ChainService has transaction concurrency of 1 

### ISSUE THREAD

**Issue by snario** [statechannels/statechannels#2993]
This might be easy to just increase, but right now the concurrency is set to 1. We definitely will need it to be higher to support funding potentially 100s of ledger channels within a somewhat small time frame. Creating this issue to track progress... maybe warrants a discussion.

**Comment by kerzhner** [comment]
I am not sure what "concurrency is set to 1" means. Perhaps this means:
- only one transaction is submitted at a time. This is necessary to avoid nonce errors. Otherwise nonce management gets tricky. Note that this restriction only applies to transaction submission. Multiple transactions can (and probably will be) mined in one block. Reference https://github.com/ethers-io/ethers.js/issues/972#issuecomment-663732420 to understand the reasons for synchronous transaction submission.
- Or maybe you mean something else by concurrency of 1?
