### ISSUE TITLE
Objectives can be nested

### ISSUE THREAD

**Issue by andrewgordstewart** [statechannels/statechannels#3227]
# Why: Problem description :confused:
Consider `closeChannel` applied to a directly funded channel. It will start a `ConcludeChannel` objective `o1`. Once the channel is concluded, it should trigger a `DefundChannel` objective `o2`.

Should `o2` follow `o1`, or should `o2` be nested in `o1`? From the app's perspective, the app wants to be told when it should no longer care about the channel. This is an argument for `o1` being nested within `o2`.

# What: Describe the solution you'd like :sparkles:  
1. The `objectives` table has a `parent_id` foreign key to itself. This turns objectives into trees.
2. `ObjectiveManager.crank(objective)` recursively cranks child objectives before cranking itself.
3. When an objective is synced, so are its child objectives.

# Describe alternatives you've considered :thinking:

The `objectives` table can have a `triggered_by` pointing to the original objective that triggered it. This seems awkward.

**Additional context**

See one possible ["data flow"](https://www.notion.so/Operations-AKA-First-Class-Objectives-826deb6b44744226b92eb4e604089e44#e66b9474f0d74eea9d758250e9245089) drawn out for `closeChannel`.

**Comment by tomclose** [comment]
I'm not sure if we need nested objectives. For example, the current `OpenChannel` protocol handles funding - there isn't a separate `FundChannel` protocol that gets started once the channel is opened. I think we'd probably want to do the same with `CloseChannel`, and automatically defund if the channel closed is a directly funded channel.

Another way of looking at this is to look at the different things that a new objective entail:

1. Do we need to get a new agreement from other participants about whether to proceed?
2. Do we need to start an objective so that the wallet will take its own actions?
3. Is it useful to separate the code out?

I'd argue that for (1) the answer is "no", as there's no alternative action with a directly funded closed channel, other than to withdraw from it. For (2) the answer is also "no", as we already have the `CloseChannel` objective, driving the process forward. For (3), the answer is yes, but we can do this anyway e.g. how `OpenChannel` calls out to the `LedgerFunder/DirectFunder/FakeFunder`.

Avoiding nested objectives would probably avoid a lot of complexity.

**Comment by wunnaii** [comment]
Requires RFC/ADR drafted

**Comment by wunnaii** [comment]
If someone feels this is important, please reopen this ticket and create an RFC/ADR
