### ISSUE TITLE
Incorrect signature index accessed

### ISSUE THREAD

**Issue by JChanceHud** [statechannels/statechannels#3765]
**Describe the bug**
The `_validSignatures` function in the `ForceMove` contract does not access the correct signature when supplying signatures/states that do not start with participant 0. e.g. `whoSignedWhat = [1, 0]`

[Here](https://github.com/statechannels/statechannels/blob/master/packages/nitro-protocol/contracts/ForceMove.sol#L427) the state hash is correctly accessed as `stateHashes[whoSignedWhat[i]]` whereas sigs is accessed simply using `sigs[i]`. Is this an intentional design because of some security/state limitation?

Changing the above line to the following resolves the bug for me and doesn't intuitively break anything:
```sol
address signer = _recoverSigner(stateHashes[whoSignedWhat[i]], sigs[whoSignedWhat[i]]);
```

**To Reproduce**
1. Create a simple state channel with two participants (User A and User B).
2. Fund the channel (`turnNum` should be 3)
3. Apply a checkpoint after two state transitions (`turnNum` should be 5) (User A should be next to make a move)
4. Submit a checkpoint using the previous state/sig from User B and a new state/sig from User A
  - The new `turnNum` should be 6. `whoSignedWhat` should be `[1, 0]`.
5. Transaction reverted `Invalid signatures`

**Expected behavior**
Transaction succeeds.

**Additional context**
[Here](https://github.com/JChanceHud/scorched/blob/fdb1adace028eaacbb451bcfd350a79f3513691d/test/scorched-test.js#L429) is a test case that triggers the bug.

**Comment by geoknee** [comment]
I think this is probably a case of underspecified / badly documented, rather than incorrect behaviour.

Implicit in the code at the moment is the requirement for signatures to conform to `[signature of participant 0, signature of participant 1, ...]`. It's this way to emphasize the importance of one signature per participant, rather than one signature per state. 

Have you tried switching the order of the signatures on [L610](https://github.com/JChanceHud/scorched/blob/fdb1adace028eaacbb451bcfd350a79f3513691d/test/scorched-test.js#L610) ? 

If this make sense to you, I'd be happy to try and improve our documentation around this. 

We also have some helper functions which aren't well advertised in the docs but may have saved you some pain here  -- for example createCheckpointTransaction https://github.com/statechannels/statechannels/blob/2a30056ca78fa3d76b11a036a891f52814846e40/packages/nitro-protocol/src/transactions.ts#L46-L55

You can access this under the `Transactions` namespace:

```ts
const {
  Transactions
} = require('@statechannels/nitro-protocol');

    const acceptTxRq = Transactions.createCheckpointTransaction([sig2, acceptSig])
    const acceptTx = await sender.sendTransaction({to: adjudicator.address, ...acceptTxRq})
```

(this passes for me when I checked out your repo).

**Comment by JChanceHud** [comment]
Thanks @geoknee, yes reordering the signatures fixes the problem.

> I think this is probably a case of underspecified / badly documented, rather than incorrect behaviour.

Yes, the `whoSignedWhat` array is a bit difficult to understand, though it makes sense that it only applies to state and not signatures themselves. A note or example around how to create a `whoSignedWhat` array for different cases might help.

More generally the docs around the JS api could definitely be improved. Samples are helpful but api docs listing what functions exist and what they do would be as helpful (otherwise you've got noobs like me trying to recreate the wheel :smiley: ).

Thanks again for the help.

**Comment by geoknee** [comment]
Thanks for this feedback @JChanceHud. I've filed #3767 and #3766 to try address it.
